import { config } from "../config.js";
import { githubManager } from "../agents/githubManager.js";
import { createId, nowIso, slugify } from "../lib/id.js";
import type {
  ActionLevel,
  JsonDatabase,
  Project,
  ProjectAction,
  ProjectError,
  ProjectInputRecord,
  ProjectStatus
} from "../../shared/types.js";

const runningStatuses: ProjectStatus[] = [
  "PROCESSING_INPUT",
  "GENERATING_PROMPT",
  "SENDING_TO_CODEX",
  "CODEX_WORKING",
  "SAVING_TO_GITHUB",
  "DEPLOYING"
];

const dossierPath = "README.md";
const stateFence = "deployrocket-state-json";

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function projectIdFor(owner: string, repo: string) {
  return Buffer.from(owner + "/" + repo, "utf8").toString("base64url");
}

export function projectRepoFromId(id: string) {
  try {
    const decoded = Buffer.from(id, "base64url").toString("utf8");
    const separator = decoded.indexOf("/");
    if (separator <= 0) return null;
    return {
      owner: decoded.slice(0, separator),
      repo: decoded.slice(separator + 1)
    };
  } catch {
    return null;
  }
}

class ProjectStore {
  async listProjects() {
    const repos = await githubManager.listDeployRocketRepositories();
    const projects = await Promise.all(
      repos.map((repo) => this.readProject(repo.owner, repo.repo, repo.branch))
    );
    return clone(
      projects
        .filter((project): project is Project => Boolean(project))
        .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
    );
  }

  async getProject(id: string) {
    const ref = projectRepoFromId(id);
    if (!ref) return null;
    return this.readProject(ref.owner, ref.repo);
  }

  async createProject(input: ProjectInputRecord) {
    const github = await githubManager.ensureAuthenticated("");
    const repository = await githubManager.createDeployRocketRepository(
      suggestRepositoryName(input),
      "Generated by deployRocket"
    );
    const now = nowIso();
    const project: Project = {
      id: projectIdFor(repository.owner, repository.repo),
      name: "Untitled project",
      summary: "Waiting for input processing.",
      status: "IDLE",
      currentStep: "Ready",
      githubRepoUrl: repository.url,
      githubOwner: repository.owner,
      githubRepo: repository.repo,
      githubUserLogin: github.user.login,
      githubDefaultBranch: repository.branch,
      error: null,
      createdAt: now,
      updatedAt: now,
      actions: [
        {
          id: createId("action"),
          at: now,
          message: "Received user input",
          level: "info",
          status: "IDLE"
        }
      ],
      inputs: [input],
      deployments: [],
      lastCommittedPaths: []
    };

    await this.writeProject(project, "Initialize deployRocket project dossier");
    return clone(project);
  }

  async addInput(projectId: string, input: ProjectInputRecord) {
    return this.updateProject(projectId, (project) => {
      project.inputs.push(input);
      project.error = null;
      this.pushAction(project, "Received edit request", "info");
    });
  }

  async updateProject(projectId: string, updater: (project: Project) => void) {
    const project = await this.getProject(projectId);
    if (!project) return null;

    updater(project);
    project.updatedAt = nowIso();
    await this.writeProject(project, "Update deployRocket project dossier");
    return clone(project);
  }

  async setStatus(
    projectId: string,
    status: ProjectStatus,
    currentStep: string,
    actionMessage?: string,
    level: ActionLevel = "info"
  ) {
    return this.updateProject(projectId, (project) => {
      project.status = status;
      project.currentStep = currentStep;
      if (status !== "FAILED") project.error = null;
      if (actionMessage) this.pushAction(project, actionMessage, level, status);
    });
  }

  async addAction(
    projectId: string,
    message: string,
    level: ActionLevel = "info",
    details?: string
  ) {
    return this.updateProject(projectId, (project) => {
      this.pushAction(project, message, level, project.status, details);
    });
  }

  async failProject(projectId: string, error: ProjectError) {
    return this.updateProject(projectId, (project) => {
      project.status = "FAILED";
      project.currentStep = "Failed";
      project.error = error;
      delete project.activeInputId;
      delete project.activeRunKind;
      delete project.pagesDispatchRequestedAt;
      delete project.continueContext;
      this.pushAction(project, error.message, "error", "FAILED", error.details);
    });
  }

  async stopProject(projectId: string, message = "Stopped by user") {
    return this.updateProject(projectId, (project) => {
      project.status = "STOPPED";
      project.currentStep = "Stopped";
      delete project.activeInputId;
      delete project.activeRunKind;
      delete project.pagesDispatchRequestedAt;
      delete project.continueContext;
      this.pushAction(project, message, "warning", "STOPPED");
    });
  }

  async adoptRepository(
    project: Project,
    repository: { owner: string; repo: string; url: string; branch: string },
    message: string,
    actionMessage?: string
  ) {
    project.id = projectIdFor(repository.owner, repository.repo);
    project.githubOwner = repository.owner;
    project.githubRepo = repository.repo;
    project.githubRepoUrl = repository.url;
    project.githubDefaultBranch = repository.branch;
    if (actionMessage) this.pushAction(project, actionMessage, "success", project.status, repository.url);
    project.updatedAt = nowIso();
    await this.writeProject(project, message);
    return clone(project);
  }

  async recoverInterruptedProjects() {
    return [] as Project[];
  }

  isRunning(status: ProjectStatus) {
    return runningStatuses.includes(status);
  }

  private async readProject(owner: string, repo: string, defaultBranch?: string) {
    const file = await githubManager.getTextFile(
      owner,
      repo,
      dossierPath,
      config.githubStateBranch
    );
    if (!file) return null;
    const parsed = parseDossier(file.content);
    if (!parsed) return null;

    parsed.id = projectIdFor(owner, repo);
    parsed.githubOwner = owner;
    parsed.githubRepo = repo;
    parsed.githubDefaultBranch = parsed.githubDefaultBranch ?? defaultBranch ?? config.githubDefaultBranch;
    return parsed;
  }

  private async writeProject(project: Project, message: string) {
    if (!project.githubOwner || !project.githubRepo) return;
    await githubManager.putTextFile({
      owner: project.githubOwner,
      repo: project.githubRepo,
      path: dossierPath,
      branch: config.githubStateBranch,
      baseBranch: project.githubDefaultBranch ?? config.githubDefaultBranch,
      content: renderDossier(project),
      message
    });
  }

  private pushAction(
    project: Project,
    message: string,
    level: ActionLevel,
    status: ProjectStatus = project.status,
    details?: string
  ) {
    const action: ProjectAction = {
      id: createId("action"),
      at: nowIso(),
      message,
      level,
      status,
      details
    };

    project.actions.push(action);
    project.actions = project.actions.slice(-250);
  }
}

function suggestRepositoryName(input: ProjectInputRecord) {
  const text = input.text.trim();
  if (!text) return "deployrocket-image-project";

  const normalized = text
    .toLowerCase()
    .replace(/mirrow/g, "mirror")
    .replace(/beckground/g, "background")
    .replace(/difrent/g, "different")
    .replace(/desaight/g, "decide");

  if (/\bmirror\b/.test(normalized) && /\bcloset\b/.test(normalized)) {
    return normalized.includes("mood") ? "mood-mirror-closet" : "virtual-mirror-closet";
  }

  const stopWords = new Set([
    "a",
    "an",
    "and",
    "app",
    "application",
    "as",
    "build",
    "client",
    "create",
    "for",
    "from",
    "in",
    "make",
    "of",
    "serverless",
    "the",
    "to",
    "user",
    "with"
  ]);
  const preferred = ["mirror", "closet", "camera", "mood", "outfit", "virtual", "background", "agent", "dashboard", "tracker"];
  const words = normalized
    .split(/[^a-z0-9]+/)
    .filter((word) => word.length > 2 && !stopWords.has(word));
  const selected = [...preferred.filter((word) => words.includes(word)), ...words]
    .filter((word, index, all) => all.indexOf(word) === index)
    .slice(0, 5);

  return slugify(selected.join("-"), "deployrocket-project");
}

function parseDossier(markdown: string): Project | null {
  const pattern = new RegExp("~~~" + stateFence + "\\n([\\s\\S]*?)\\n~~~", "m");
  const match = markdown.match(pattern);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[1]) as Project;
    return parsed && typeof parsed.id === "string" ? parsed : null;
  } catch {
    return null;
  }
}

function renderDossier(project: Project) {
  const latestInput = project.inputs.at(-1);
  const promptPlan = latestInput?.codexPrompt;
  const requirements = latestInput?.structuredRequirements;
  const complete = project.status === "LIVE";

  return [
    "# deployRocket Project Dossier",
    "",
    "This branch is managed by deployRocket. It intentionally stores only this dossier README as machine-readable and human-readable project memory.",
    "",
    "Generated application files are committed to the repository default branch after Codex returns a valid file set. If the default branch only has an initial README, code generation has not succeeded yet.",
    "",
    "## Agent State",
    "",
    "~~~" + stateFence,
    JSON.stringify(project, null, 2),
    "~~~",
    "",
    "## Status",
    "",
    "Current stage: **" + project.currentStep + "**",
    "",
    "Complete: **" + (complete ? "yes" : "no") + "**",
    "",
    renderStages(project),
    "",
    "## Project",
    "",
    "Name: " + project.name,
    "",
    "Summary: " + project.summary,
    "",
    "Repository: " + (project.githubRepoUrl ?? "pending"),
    "",
    "Code branch: " + (project.githubDefaultBranch ?? config.githubDefaultBranch),
    "",
    "State branch: " + config.githubStateBranch,
    "",
    "Live URL: " + (project.githubPagesUrl ?? "pending"),
    "",
    "## Original Prompt",
    "",
    latestInput?.text || "(image-only request)",
    "",
    "## Architecture And Prompt",
    "",
    requirements ? "### Structured Requirements\n\n~~~json\n" + JSON.stringify(requirements, null, 2) + "\n~~~" : "Structured requirements are pending.",
    "",
    promptPlan ? "### Codex Prompt Plan\n\n~~~json\n" + JSON.stringify(promptPlan, null, 2) + "\n~~~" : "Codex prompt plan is pending.",
    "",
    "## Action History",
    "",
    ...project.actions.slice(-80).map((action) => {
      const suffix = action.details ? " - " + action.details : "";
      return "- " + action.at + " - " + action.message + " (" + action.level + ")" + suffix;
    }),
    "",
    project.error ? "## Latest Error\n\n" + project.error.message + "\n\n~~~text\n" + (project.error.details ?? "") + "\n~~~" : "## Latest Error\n\nNone.",
    ""
  ].join("\n");
}

function renderStages(project: Project) {
  const stages: Array<[ProjectStatus | "RECEIVED", string]> = [
    ["RECEIVED", "Received user prompt"],
    ["PROCESSING_INPUT", "Generated product requirements"],
    ["GENERATING_PROMPT", "Created architecture plan"],
    ["CODEX_WORKING", "Generated project code"],
    ["SAVING_TO_GITHUB", "Committed files to GitHub"],
    ["DEPLOYING", "Deployed to GitHub Pages"],
    ["LIVE", "Verified live URL"]
  ];

  return [
    "| Stage | State |",
    "| --- | --- |",
    ...stages.map(([status, label]) => "| " + label + " | " + stageState(project, status) + " |")
  ].join("\n");
}

function stageState(project: Project, stage: ProjectStatus | "RECEIVED") {
  if (stage === "RECEIVED") return "done";
  if (project.status === "LIVE") return "done";

  const order: Array<ProjectStatus | "RECEIVED"> = [
    "RECEIVED",
    "PROCESSING_INPUT",
    "GENERATING_PROMPT",
    "CODEX_WORKING",
    "SAVING_TO_GITHUB",
    "DEPLOYING",
    "LIVE"
  ];
  const active = normalizeStage(project.status === "FAILED" ? latestWorkingStatus(project) : project.status);
  const stageIndex = order.indexOf(stage);
  const activeIndex = order.indexOf(active);

  if (project.status === "FAILED" && stage === active) return "failed";
  if (project.status === "STOPPED" && stage === active) return "stopped";
  if (activeIndex > -1 && stageIndex < activeIndex) return "done";
  if (activeIndex > -1 && stageIndex === activeIndex) return project.status === "FAILED" ? "failed" : "current";
  return "pending";
}

function latestWorkingStatus(project: Project) {
  return (
    [...project.actions]
      .reverse()
      .find((action) => action.status && action.status !== "FAILED" && action.status !== "STOPPED")
      ?.status ?? "IDLE"
  );
}

function normalizeStage(status: ProjectStatus | "RECEIVED") {
  if (status === "SENDING_TO_CODEX") return "CODEX_WORKING";
  if (status === "IDLE") return "RECEIVED";
  return status;
}

export const projectStore = new ProjectStore();
export const runningProjectStatuses = runningStatuses;
export type { JsonDatabase };
