import { config } from "../config.js";
import { githubManager } from "../agents/githubManager.js";
import { createId, nowIso, slugify } from "../lib/id.js";
import type {
  ActionLevel,
  JsonDatabase,
  Project,
  ProjectAction,
  ProjectError,
  ProjectInputRecord,
  ProjectStatus
} from "../../shared/types.js";

const runningStatuses: ProjectStatus[] = [
  "PROCESSING_INPUT",
  "GENERATING_PROMPT",
  "SENDING_TO_CODEX",
  "CODEX_WORKING",
  "SAVING_TO_GITHUB",
  "DEPLOYING"
];

const dossierPath = "README.md";
const stateFence = "deployrocket-state-json";

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function projectIdFor(owner: string, repo: string) {
  return Buffer.from(owner + "/" + repo, "utf8").toString("base64url");
}

export function projectRepoFromId(id: string) {
  try {
    const decoded = Buffer.from(id, "base64url").toString("utf8");
    const separator = decoded.indexOf("/");
    if (separator <= 0) return null;
    return {
      owner: decoded.slice(0, separator),
      repo: decoded.slice(separator + 1)
    };
  } catch {
    return null;
  }
}

class ProjectStore {
  async listProjects() {
    const repos = await githubManager.listDeployRocketRepositories();
    const projects = await Promise.all(
      repos.map((repo) => this.readProject(repo.owner, repo.repo, repo.branch))
    );
    return clone(
      projects
        .filter((project): project is Project => Boolean(project))
        .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
    );
  }

  async getProject(id: string) {
    const ref = projectRepoFromId(id);
    if (!ref) return null;
    return this.readProject(ref.owner, ref.repo);
  }

  async createProject(input: ProjectInputRecord) {
    const github = await githubManager.ensureAuthenticated("");
    const repository = await githubManager.createDeployRocketRepository(
      suggestRepositoryName(input),
      "Generated by deployRocket"
    );
    const now = nowIso();
    const project: Project = {
      id: projectIdFor(repository.owner, repository.repo),
      name: "Untitled project",
      summary: "Waiting for input processing.",
      status: "IDLE",
      currentStep: "Ready",
      githubRepoUrl: repository.url,
      githubOwner: repository.owner,
      githubRepo: repository.repo,
      githubUserLogin: github.user.login,
      githubDefaultBranch: repository.branch,
      error: null,
      createdAt: now,
      updatedAt: now,
      actions: [
        {
          id: createId("action"),
          at: now,
          message: "Received user input",
          level: "info",
          status: "IDLE"
        }
      ],
      inputs: [input],
      deployments: [],
      lastCommittedPaths: []
    };

    await this.writeProject(project, "Initialize deployRocket project dossier");
    return clone(project);
  }

  async addInput(projectId: string, input: ProjectInputRecord) {
    return this.updateProject(projectId, (project) => {
      project.inputs.push(input);
      project.error = null;
      this.pushAction(project, "Received edit request", "info");
    });
  }

  async updateProject(projectId: string, updater: (project: Project) => void) {
    const project = await this.getProject(projectId);
    if (!project) return null;

    updater(project);
    project.updatedAt = nowIso();
    await this.writeProject(project, "Update deployRocket project dossier");
    return clone(project);
  }

  async setStatus(
    projectId: string,
    status: ProjectStatus,
    currentStep: string,
    actionMessage?: string,
    level: ActionLevel = "info"
  ) {
    return this.updateProject(projectId, (project) => {
      project.status = status;
      project.currentStep = currentStep;
      if (status !== "FAILED") project.error = null;
      if (actionMessage) this.pushAction(project, actionMessage, level, status);
    });
  }

  async addAction(
    projectId: string,
    message: string,
    level: ActionLevel = "info",
    details?: string
  ) {
    return this.updateProject(projectId, (project) => {
      this.pushAction(project, message, level, project.status, details);
    });
  }

  async failProject(projectId: string, error: ProjectError) {
    return this.updateProject(projectId, (project) => {
      project.status = "FAILED";
      project.currentStep = "Failed";
      project.error = error;
      delete project.activeInputId;
      delete project.activeRunKind;
      delete project.pagesDispatchRequestedAt;
      this.pushAction(project, error.message, "error", "FAILED", error.details);
    });
  }

  async stopProject(projectId: string, message = "Stopped by user") {
    return this.updateProject(projectId, (project) => {
      project.status = "STOPPED";
      project.currentStep = "Stopped";
      delete project.activeInputId;
      delete project.activeRunKind;
      delete project.pagesDispatchRequestedAt;
      this.pushAction(project, message, "warning", "STOPPED");
    });
  }

  async recoverInterruptedProjects() {
    return [] as Project[];
  }

  isRunning(status: ProjectStatus) {
    return runningStatuses.includes(status);
  }

  private async readProject(owner: string, repo: string, defaultBranch?: string) {
    const file = await githubManager.getTextFile(
      owner,
      repo,
      dossierPath,
      config.githubStateBranch
    );
    if (!file) return null;
    const parsed = parseDossier(file.content);
    if (!parsed) return null;

    parsed.id = projectIdFor(owner, repo);
    parsed.githubOwner = owner;
    parsed.githubRepo = repo;
    parsed.githubDefaultBranch = parsed.githubDefaultBranch ?? defaultBranch ?? config.githubDefaultBranch;
    return parsed;
  }

  private async writeProject(project: Project, message: string) {
    if (!project.githubOwner || !project.githubRepo) return;
    await githubManager.putTextFile({
      owner: project.githubOwner,
      repo: project.githubRepo,
      path: dossierPath,
      branch: config.githubStateBranch,
      baseBranch: project.githubDefaultBranch ?? config.githubDefaultBranch,
      content: renderDossier(project),
      message
    });
  }

  private pushAction(
    project: Project,
    message: string,
    level: ActionLevel,
    status: ProjectStatus = project.status,
    details?: string
  ) {
    const action: ProjectAction = {
      id: createId("action"),
      at: nowIso(),
      message,
      level,
      status,
      details
    };

    project.actions.push(action);
    project.actions = project.actions.slice(-250);
  }
}

function suggestRepositoryName(input: ProjectInputRecord) {
  const text = input.text.trim();
  if (!text) return "deployrocket-image-project";
  const words = text.split(/\s+/).slice(0, 8).join(" ");
  return slugify(words, "deployrocket-project");
}

function parseDossier(markdown: string): Project | null {
  const pattern = new RegExp("~~~" + stateFence + "\\n([\\s\\S]*?)\\n~~~", "m");
  const match = markdown.match(pattern);
  if (!match) return null;
  try {
    const parsed = JSON.parse(match[1]) as Project;
    return parsed && typeof parsed.id === "string" ? parsed : null;
  } catch {
    return null;
  }
}

function renderDossier(project: Project) {
  const latestInput = project.inputs.at(-1);
  const promptPlan = latestInput?.codexPrompt;
  const requirements = latestInput?.structuredRequirements;
  const complete = project.status === "LIVE";

  return [
    "# deployRocket Project Dossier",
    "",
    "This branch is managed by deployRocket. It is the machine-readable and human-readable project memory for agents, status screens, and redeploys.",
    "",
    "## Agent State",
    "",
    "~~~" + stateFence,
    JSON.stringify(project, null, 2),
    "~~~",
    "",
    "## Status",
    "",
    "Current stage: **" + project.currentStep + "**",
    "",
    "Complete: **" + (complete ? "yes" : "no") + "**",
    "",
    renderStages(project),
    "",
    "## Project",
    "",
    "Name: " + project.name,
    "",
    "Summary: " + project.summary,
    "",
    "Repository: " + (project.githubRepoUrl ?? "pending"),
    "",
    "Live URL: " + (project.githubPagesUrl ?? "pending"),
    "",
    "## Original Prompt",
    "",
    latestInput?.text || "(image-only request)",
    "",
    "## Architecture And Prompt",
    "",
    requirements ? "### Structured Requirements\n\n~~~json\n" + JSON.stringify(requirements, null, 2) + "\n~~~" : "Structured requirements are pending.",
    "",
    promptPlan ? "### Codex Prompt Plan\n\n~~~json\n" + JSON.stringify(promptPlan, null, 2) + "\n~~~" : "Codex prompt plan is pending.",
    "",
    "## Action History",
    "",
    ...project.actions.slice(-80).map((action) => {
      const suffix = action.details ? " - " + action.details : "";
      return "- " + action.at + " - " + action.message + " (" + action.level + ")" + suffix;
    }),
    "",
    project.error ? "## Latest Error\n\n" + project.error.message + "\n\n~~~text\n" + (project.error.details ?? "") + "\n~~~" : "## Latest Error\n\nNone.",
    ""
  ].join("\n");
}

function renderStages(project: Project) {
  const stages: Array<[ProjectStatus | "RECEIVED", string]> = [
    ["RECEIVED", "Received user prompt"],
    ["PROCESSING_INPUT", "Generated product requirements"],
    ["GENERATING_PROMPT", "Created architecture plan"],
    ["CODEX_WORKING", "Generated project code"],
    ["SAVING_TO_GITHUB", "Committed files to GitHub"],
    ["DEPLOYING", "Deployed to GitHub Pages"],
    ["LIVE", "Verified live URL"]
  ];
  const order = [
    "IDLE",
    "PROCESSING_INPUT",
    "GENERATING_PROMPT",
    "SENDING_TO_CODEX",
    "CODEX_WORKING",
    "SAVING_TO_GITHUB",
    "DEPLOYING",
    "LIVE"
  ];
  const currentIndex = order.indexOf(project.status);

  return stages
    .map(([status, label]) => {
      const checked =
        status === "RECEIVED" ||
        project.status === "LIVE" ||
        (typeof status === "string" && order.indexOf(status as ProjectStatus) < currentIndex);
      return "- [" + (checked ? "x" : " ") + "] " + label;
    })
    .join("\n");
}

export const projectStore = new ProjectStore();
export const runningProjectStatuses = runningStatuses;
export type { JsonDatabase };
